[lastfm]
user_name = "foobar"
password = "hunter2"
# Create these here: http://www.last.fm/api/account/create
api_key = "..."
api_secret = "..."

[librefm]
user_name = "foobar"
password = "hunter2"
# Run lastcast --wizard to populate this
session_key = "..."

[chromecast]
# chromecast devices to listen to, this can also include group names.
devices = ["Living Room", "My Group"]
# (optional) list of chrome cast apps to scrobble from
app_whitelist = ["Spotify", "Google Play Music"]
# (optional) estimate the timestamp for tracks on spotify (see issues #20, #27)
#            this will prevent seeking from working properly. defaults to true
estimate_spotify_timestamp = true
# (optional) ignore devices that aren't found during startup. Defaults to false.
ignore_missing = false
# (optional) don't fail when a device isn't found, continue to retry
#            connecting to it. Useful if one or more of the devices are
#            not always on. Defaults to false.
#
# NOTE: This flag is potentially buggy and may cause lastcast to hang on
#       particularly volatile networks. Please report any bugs.
retry_missing = false
