[lastfm]
user_name = "foobar"
password = "hunter2"
# Create these here: http://www.last.fm/api/account/create
api_key = "..."
api_secret = "..."

[librefm]
user_name = "foobar"
password = "hunter2"
# Run lastcast --wizard to populate this
session_key = "..."

[chromecast]
# chromecast devices to listen to, this can also include group names.
devices = ["Living Room", "My Group"]
# (optional) list of chrome cast apps to scrobble from
app_whitelist = ["Spotify", "Google Play Music"]
# (optional) estimate the timestamp for tracks on spotify (see issues #20, #27)
#            this will prevent seeking from working properly. defaults to true
estimate_spotify_timestamp = true
